# Generated by Django 5.2.3 on 2025-07-15 19:35

import pal_learning_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pal_learning_app', '0002_alter_customuser_managers_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', pal_learning_app.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
